/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zastosowanieProgramowaniaKomponentowego;

import java.awt.Color;
import java.awt.Font;
import javax.swing.SwingConstants;

/**
 *
 * @author Julia
 */
public class TestCalcComponent extends javax.swing.JFrame {

    /**
     * Creates new form TestCalcComponent
     */
    public TestCalcComponent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calculatorPanel1 = new com.mycompany.zastosowanieProgramowaniaKomponentowego.Components.Calculator.CalculatorPanel();
        showABPlaceHoldersCB = new javax.swing.JCheckBox();
        showResultPlaceHolderCB = new javax.swing.JCheckBox();
        changeTitleColorGreenTF = new javax.swing.JTextField();
        changeTitleColorBlueTF = new javax.swing.JTextField();
        submitNewColor = new javax.swing.JButton();
        resultAlignementCB = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        changeTitleColorRedTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fontCB = new javax.swing.JComboBox<>();
        resultAlignementCB1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        showABPlaceHoldersCB.setSelected(true);
        showABPlaceHoldersCB.setText("show A and B placeholders");
        showABPlaceHoldersCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showABPlaceHoldersCBActionPerformed(evt);
            }
        });

        showResultPlaceHolderCB.setSelected(true);
        showResultPlaceHolderCB.setText("show result placeholder");
        showResultPlaceHolderCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showResultPlaceHolderCBActionPerformed(evt);
            }
        });

        submitNewColor.setText("submit RGB");
        submitNewColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitNewColorActionPerformed(evt);
            }
        });

        resultAlignementCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "center", "left", "right" }));
        resultAlignementCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultAlignementCBActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Result alignement");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Title color");

        jLabel7.setText("R");

        jLabel8.setText("G");

        jLabel9.setText("B");

        fontCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monospaced", "Times New Roman", "Baskerville Old Face" }));
        fontCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontCBActionPerformed(evt);
            }
        });
        fontCB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fontCBPropertyChange(evt);
            }
        });

        resultAlignementCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        resultAlignementCB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultAlignementCB1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Result decimals");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showABPlaceHoldersCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showResultPlaceHolderCB)
                            .addComponent(fontCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resultAlignementCB, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resultAlignementCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(changeTitleColorRedTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(changeTitleColorGreenTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(changeTitleColorBlueTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(submitNewColor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(calculatorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(calculatorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changeTitleColorRedTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeTitleColorGreenTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeTitleColorBlueTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitNewColor))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fontCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultAlignementCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultAlignementCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(showABPlaceHoldersCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(showResultPlaceHolderCB)
                                .addGap(9, 9, 9)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showABPlaceHoldersCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showABPlaceHoldersCBActionPerformed
       calculatorPanel1.showHeightAndRadiusPlaceHolders(showABPlaceHoldersCB.isSelected());
    }//GEN-LAST:event_showABPlaceHoldersCBActionPerformed

    private void showResultPlaceHolderCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showResultPlaceHolderCBActionPerformed
        calculatorPanel1.showResultPlaceHolder(showResultPlaceHolderCB.isSelected());
    }//GEN-LAST:event_showResultPlaceHolderCBActionPerformed

    private void submitNewColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitNewColorActionPerformed
        calculatorPanel1.setTitleColor(createColorFromRGBTextFields());
    }//GEN-LAST:event_submitNewColorActionPerformed
    
    private Color createColorFromRGBTextFields(){
        
        try{
            Integer r = Integer.valueOf(changeTitleColorRedTF.getText());
            Integer g = Integer.valueOf(changeTitleColorGreenTF.getText());
            Integer b = Integer.valueOf(changeTitleColorBlueTF.getText());
        
            if(r<=255 && r>=0 && g<=255 && g>=0 && b<=255 && b>=0){
                return new Color(r,g,b);
            }else throw new NumberFormatException();
            
        }catch(NumberFormatException ex){
            System.out.println("Nieprawidłowy kolor. R, G i B muszą wynosić 0-255.");
            return Color.BLACK;
        }
    }
    
    private void resultAlignementCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultAlignementCBActionPerformed
        Integer alignement;

        if(resultAlignementCB.getSelectedItem()=="center")
            alignement = SwingConstants.CENTER;
        else if(resultAlignementCB.getSelectedItem()=="left")
            alignement = SwingConstants.LEFT;
        else if(resultAlignementCB.getSelectedItem()=="right")
            alignement = SwingConstants.RIGHT;
        else alignement = SwingConstants.CENTER;

        calculatorPanel1.setResultAlignement(alignement);

    }//GEN-LAST:event_resultAlignementCBActionPerformed

    private void fontCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontCBActionPerformed
        System.out.println("ZMIANA FONTU");
        Font font;
       
        switch (fontCB.getSelectedIndex()) {
            case 0:
                font = new Font("Monospaced", Font.PLAIN, 24);
                break;
            case 1:
                font = new Font("Times New Roman", Font.PLAIN, 24);
                break;
            default:
                font = new Font("Baskerville Old Face", Font.PLAIN, 24);
                break;
        }
        
        calculatorPanel1.setTitleFont(font);
    }//GEN-LAST:event_fontCBActionPerformed

    private void fontCBPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fontCBPropertyChange
       Font font;
       
        switch (fontCB.getSelectedIndex()) {
            case 0:
                font = new Font("Monospaced", Font.PLAIN, 24);
                break;
            case 1:
                font = new Font("Times New Roman", Font.PLAIN, 24);
                break;
            default:
                font = new Font("Baskerville Old Face", Font.PLAIN, 34);
                break;
        }
        
        calculatorPanel1.setTitleFont(font);

    }//GEN-LAST:event_fontCBPropertyChange

    private void resultAlignementCB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultAlignementCB1ActionPerformed
         switch (resultAlignementCB1.getSelectedIndex()){
            case 0:
                 calculatorPanel1.setNumberOfDecimals(0);
                 break;
            case 1:
                 calculatorPanel1.setNumberOfDecimals(1);
                 break;
            case 2:
                 calculatorPanel1.setNumberOfDecimals(2);
                 break;
                 
            case 3:
                 calculatorPanel1.setNumberOfDecimals(3);
                 break;
            case 4:
                 calculatorPanel1.setNumberOfDecimals(4);
                 break;
            default:
                 calculatorPanel1.setNumberOfDecimals(5);
                 break;
         }
    }//GEN-LAST:event_resultAlignementCB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestCalcComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestCalcComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestCalcComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestCalcComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestCalcComponent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.zastosowanieProgramowaniaKomponentowego.Components.Calculator.CalculatorPanel calculatorPanel1;
    private javax.swing.JTextField changeTitleColorBlueTF;
    private javax.swing.JTextField changeTitleColorGreenTF;
    private javax.swing.JTextField changeTitleColorRedTF;
    private javax.swing.JComboBox<String> fontCB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> resultAlignementCB;
    private javax.swing.JComboBox<String> resultAlignementCB1;
    private javax.swing.JCheckBox showABPlaceHoldersCB;
    private javax.swing.JCheckBox showResultPlaceHolderCB;
    private javax.swing.JButton submitNewColor;
    // End of variables declaration//GEN-END:variables
}
