/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.mycompany.components;

import java.awt.Color;
import java.util.Objects;
import javax.swing.JTextField;

/**
 *
 * @author Julia
 */
public class NumericKeyboard extends javax.swing.JPanel {

    JTextField lastTF;
    CylinderCalculator connectedCalculator;
    /** Creates new form NumericKeyboard */
    public NumericKeyboard() {
//        this.connectedCalculator = cc;
        initComponents();
    }

    public NumericKeyboard(CylinderCalculator cc) {
        this.connectedCalculator = cc;
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nr1Button = new java.awt.Button();
        nr2Button = new java.awt.Button();
        nr3Button = new java.awt.Button();
        nr4Button = new java.awt.Button();
        nr5Button = new java.awt.Button();
        nr6Button = new java.awt.Button();
        nr7Button = new java.awt.Button();
        nr8Button = new java.awt.Button();
        nr9Button = new java.awt.Button();
        resetButton = new java.awt.Button();
        nextTFButton = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        switchEditedTFButton = new java.awt.Button();

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 250));
        jPanel2.setLayout(new java.awt.GridLayout(0, 3));

        nr1Button.setLabel("1");
        nr1Button.setMinimumSize(new java.awt.Dimension(50, 50));
        nr1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nr1Button);

        nr2Button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nr2Button.setLabel("2");
        nr2Button.setMinimumSize(new java.awt.Dimension(50, 50));
        nr2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrButtonActionPerformed(evt);
            }
        });
        nr2Button.setFocusable(false);
        jPanel2.add(nr2Button);

        nr3Button.setLabel("3");
        nr3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nr3Button);

        nr4Button.setLabel("4");
        nr4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nr4Button);

        nr5Button.setLabel("5");
        nr5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nr5Button);

        nr6Button.setLabel("6");
        nr6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nr6Button);

        nr7Button.setLabel("7");
        nr7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nr7Button);

        nr8Button.setLabel("8");
        nr8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nr8Button);

        nr9Button.setLabel("9");
        nr9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nr9Button);

        resetButton.setLabel("reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel2.add(resetButton);

        nextTFButton.setLabel("0");
        nextTFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nextTFButton);

        switchEditedTFButton.setLabel("-->");
        switchEditedTFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchEditedTFButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(switchEditedTFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(switchEditedTFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void nrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrButtonActionPerformed
        lastTF = connectedCalculator.getLastTF();
        if(!Objects.isNull(lastTF)){
            String tfNewText = lastTF.getText();
            lastTF.setText(evt.getActionCommand());

            if(tfNewText.equals(connectedCalculator.getHeightTFPlaceholder()) || tfNewText.equals(connectedCalculator.getRadiusTFPlaceholder()) ){
                tfNewText = evt.getActionCommand();
            }
            else {
                tfNewText = tfNewText+evt.getActionCommand();
            }
            lastTF.setText(tfNewText);
            lastTF.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_nrButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        connectedCalculator.resetParametersTF();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void switchEditedTFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchEditedTFButtonActionPerformed
        connectedCalculator.switchLastTF();
        lastTF = connectedCalculator.getLastTF();
    }//GEN-LAST:event_switchEditedTFButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Button nextTFButton;
    private java.awt.Button nr1Button;
    private java.awt.Button nr2Button;
    private java.awt.Button nr3Button;
    private java.awt.Button nr4Button;
    private java.awt.Button nr5Button;
    private java.awt.Button nr6Button;
    private java.awt.Button nr7Button;
    private java.awt.Button nr8Button;
    private java.awt.Button nr9Button;
    private java.awt.Button resetButton;
    private java.awt.Button switchEditedTFButton;
    // End of variables declaration//GEN-END:variables

}
