/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.mycompany.zastosowanieProgramowaniaKomponentowego.Components;

/**
 *
 * @author Julia
 */
public class Keyboard extends javax.swing.JPanel {

    /** Creates new form Keyboard */
    public Keyboard() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button2 = new java.awt.Button();
        button9 = new java.awt.Button();
        nr1Button = new java.awt.Button();
        nr2Button = new java.awt.Button();
        nr3Button = new java.awt.Button();
        nr4Button = new java.awt.Button();
        nr5Button = new java.awt.Button();
        nr6Button = new java.awt.Button();
        nr7Button = new java.awt.Button();
        nr8Button = new java.awt.Button();
        nr9Button = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        nr10Button = new java.awt.Button();

        button2.setLabel("button2");

        button9.setLabel("button9");

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(200, 250));
        setLayout(new java.awt.GridLayout(0, 3));

        nr1Button.setLabel("1");
        nr1Button.setMinimumSize(new java.awt.Dimension(50, 50));
        nr1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nr1ButtonActionPerformed(evt);
            }
        });
        add(nr1Button);
        nr1Button.getAccessibleContext().setAccessibleName("nr1Button");

        nr2Button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nr2Button.setLabel("2");
        nr2Button.setMinimumSize(new java.awt.Dimension(50, 50));
        nr2Button.setFocusable(false);
        add(nr2Button);
        nr2Button.getAccessibleContext().setAccessibleName("nr2Button");

        nr3Button.setLabel("3");
        add(nr3Button);

        nr4Button.setLabel("4");
        add(nr4Button);

        nr5Button.setLabel("5");
        add(nr5Button);

        nr6Button.setLabel("6");
        add(nr6Button);

        nr7Button.setLabel("7");
        add(nr7Button);

        nr8Button.setLabel("8");
        add(nr8Button);

        nr9Button.setLabel("9");
        add(nr9Button);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        add(jPanel1);

        nr10Button.setLabel("0");
        add(nr10Button);
    }// </editor-fold>//GEN-END:initComponents

    private void nr1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nr1ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nr1ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button2;
    private java.awt.Button button9;
    private javax.swing.JPanel jPanel1;
    private java.awt.Button nr10Button;
    private java.awt.Button nr1Button;
    private java.awt.Button nr2Button;
    private java.awt.Button nr3Button;
    private java.awt.Button nr4Button;
    private java.awt.Button nr5Button;
    private java.awt.Button nr6Button;
    private java.awt.Button nr7Button;
    private java.awt.Button nr8Button;
    private java.awt.Button nr9Button;
    // End of variables declaration//GEN-END:variables

}
